name: Build Conda packages

permissions:
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build_conda:
    name: Build Conda package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target-platform: linux-64
          #- os: windows-latest
          #  target-platform: win-64
          - os: macos-15
            target-platform: osx-arm64
    steps:
      - uses: actions/checkout@v4

      - name: Build conda packages & upload as workflow artifact
        uses: prefix-dev/rattler-build-action@v0.2.34
        with:
          artifact-name: package-${{ matrix.target-platform }}
          build-args: --experimental --target-platform ${{ matrix.target-platform }}${{ matrix.target-platform == 'linux-aarch64' && ' --no-test' || '' }}

      - name: Upload conda packages to prefix.dev
        shell: bash
        # do not upload on PR
        if: github.event_name == 'push'
        run: |
          # uses trusted publishers for the upload
          for file in output/**/*.conda; do
            rattler-build upload prefix -c vilma "$file"
          done

      - name: Upload conda packages to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output/**/*.conda
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
