name: Build Conda

on: [push, pull_request]

jobs:
  build_conda:
    name: Build Conda package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-14]

    steps:
      - uses: actions/checkout@v5

      - uses: prefix-dev/setup-pixi@v0.9.2
        with:
          pixi-version: v0.59.0
          cache: true

      - name: Pixi build
        run: |
         pixi build

      - uses: actions/upload-artifact@v4
        with:
          name: conda-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./*.conda
