name: Test

on: [push, pull_request]

jobs:
  build_conda:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - name: Install Python package
        run: |
          uv sync --dev

      - name: Run basedpyright
        run: |
          basedpyright
