name: Tests

on: [push, pull_request]

jobs:
  typecheck_python:
    name: Typecheck Python
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - name: Install Python package
        run: |
          uv sync --dev

      - name: Run basedpyright
        run: |
          uv run basedpyright --level=error $(uv run python -c 'import apitofsim; import os; print(os.path.dirname(apitofsim.__file__))')

      - name: Run basedpyright with warnings
        run: |
          uv run basedpyright $(uv run python -c 'import apitofsim; import os; print(os.path.dirname(apitofsim.__file__))')

      - name: Run basedpyright coverage
        run: |
          uv run basedpyright --verifytypes apitofsim || true # Ignore failures for now

  lint_python:
    name: Style check Python
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v5

      - name: Ruff check
        uses: astral-sh/ruff-action@v3
        with:
          args: "check"
          src: "./python"

      - name: Ruff format check
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
          src: "./python"

  linters_cpp:
    name: Style check C++
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          sudo apt-get install -y meson clang-tidy-20 clang-format-20 clang-20 lld-20
          sudo ln -s /usr/bin/clang-tidy-20 /usr/bin/clang-tidy
          sudo ln -s /usr/bin/clang-format-20 /usr/bin/clang-format
          sudo ln -s /usr/bin/clang++-20 /usr/bin/clang++
          sudo ln -s /usr/bin/lld-20 /usr/bin/lld

      - name: Build with meson
        run: |
          CXX="clang++" LD="lld" meson setup -warnlevel 3 -werror build
          meson compile -C build

      - name: Run clang-format-check
        run: |
          ninja -C build clang-format-check

      - name: Run clang-tidy
        run: |
          ninja -C build clang-tidy
