name: Tests

on: [push, pull_request]

jobs:
  typecheck_python:
    name: Typecheck Python
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - name: Install Python package
        run: |
          uv sync --dev

      - name: Run basedpyright
        run: |
          uv run basedpyright --level=error $(python -c 'import apitofsim; import os; print(os.path.dirname(apitofsim.__file__))')

      - name: Run basedpyright with warnings
        run: |
          uv run basedpyright $(python -c 'import apitofsim; import os; print(os.path.dirname(apitofsim.__file__))')

      - name: Run basedpyright coverage
        run: |
          uv run basedpyright --verifytypes apitofsim || true # Ignore failures for now

  lint_python:
    name: Typecheck Python
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - name: Install Python package
        run: |
          uv sync --dev

      - name: Run ruff
        run: |
          uv run ruff python

  linters_cpp:
    name: C++ linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install meson
        run: |
          sudo apt-get install -y meson

      - name: Build with meson
        run: |
          meson setup build
          meson compile -C build

      - name: Run clang-tidy
        run: |
          meson tidy -C build

      - name: Copy compile_commands.json
        run: |
          cp build/compile_commands.json .

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.16.0
        with:
          clang-format-version: '21'
