name: Tests

on: [push, pull_request]

jobs:
  typecheck_python:
    name: Typecheck Python
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - name: Install Python package
        run: |
          uv sync --dev

      - name: Run basedpyright
        run: |
          uv run basedpyright --level=error $(uv run python -c 'import apitofsim; import os; print(os.path.dirname(apitofsim.__file__))')

      - name: Run basedpyright with warnings
        run: |
          uv run basedpyright $(uv run python -c 'import apitofsim; import os; print(os.path.dirname(apitofsim.__file__))')

      - name: Run basedpyright coverage
        run: |
          uv run basedpyright --verifytypes apitofsim || true # Ignore failures for now

  lint_python:
    name: Style check Python
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/ruff-action@v3

      - run: ruff check ./python

      - run: ruff format --check ./python

  linters_cpp:
    name: Style check C++
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          sudo apt-get install -y meson ninja clang-tidy clang-format

      - name: Build with meson
        run: |
          meson setup --native-file meson/clangdebug.ini debugbuild

      - name: Run clang-format-check
        run: |
          ninja -C debugbuild clang-format-check

      - name: Run clang-tidy
        run: |
          ninja -C debugbuild clang-tidy
