name: Tests

on: [push, pull_request]

jobs:
  linters_python:
    name: Python linters
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - name: Install Python package
        run: |
          uv sync --dev

      - name: Run basedpyright
        run: |
          uv run basedpyright

  linters_cpp:
    name: C++ linters
    runs-on: ubuntu-slim

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Run clang-tidy
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: tidy

      - name: Copy compile_commands.json
        run: |
          cp build/compile_commands.json .

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.16.0
        with:
          clang-format-version: '21'

  build_old:
    name: Test build possible on old Debian (Bullseye)
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    steps:
      - name: Build / compile
        run: |
          apt-get -y install build-essential meson
          meson setup build
          meson compile -C build
